storage:
  _type: es
  host: localhost      # es host
  port: 9200          # es port
  username: elastic   # es username
  password: changeme  # es password
  index: gateway-*
api:
  enable: true
  port: 3131
  basic_auth:
    enable: true
    username: admin
    password: 123456
alert:
  _type: mail             # alert type
  username: fudali4test@163.com
  password: 1234567890abc
  smtp_host: smtp.163.com
  smtp_port: 25
  send_to:
    - fudali4test@163.com
  from_addr: fudali4test@163.com             # 显示发送出去的用户是谁
  reply_to: fudali4test@163.com              # 发送出去的邮件回复给谁
